# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coilGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 834)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_resource = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_resource.setObjectName("lineEdit_resource")
        self.gridLayout_2.addWidget(self.lineEdit_resource, 0, 1, 1, 1)
        self.label_deviceName = QtWidgets.QLabel(self.groupBox)
        self.label_deviceName.setObjectName("label_deviceName")
        self.gridLayout_2.addWidget(self.label_deviceName, 1, 0, 1, 1)
        self.checkBox_connect = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_connect.setObjectName("checkBox_connect")
        self.gridLayout_2.addWidget(self.checkBox_connect, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_6.addWidget(self.lcdNumber)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_5.addWidget(self.lcdNumber_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.lcd2_volt = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcd2_volt.setObjectName("lcd2_volt")
        self.verticalLayout_7.addWidget(self.lcd2_volt)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.lcd2_curr = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcd2_curr.setObjectName("lcd2_curr")
        self.verticalLayout_8.addWidget(self.lcd2_curr)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.verticalLayout_9.addWidget(self.lcdNumber_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.verticalLayout_10.addWidget(self.lcdNumber_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_deviceControl = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_deviceControl.setEnabled(True)
        self.groupBox_deviceControl.setObjectName("groupBox_deviceControl")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_deviceControl)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_output = QtWidgets.QCheckBox(self.groupBox_deviceControl)
        self.checkBox_output.setEnabled(False)
        self.checkBox_output.setObjectName("checkBox_output")
        self.horizontalLayout_9.addWidget(self.checkBox_output)
        self.checkBox_automaticcontrol = QtWidgets.QCheckBox(self.groupBox_deviceControl)
        self.checkBox_automaticcontrol.setObjectName("checkBox_automaticcontrol")
        self.horizontalLayout_9.addWidget(self.checkBox_automaticcontrol)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_deviceControl)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radio_cc1 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radio_cc1.setObjectName("radio_cc1")
        self.horizontalLayout_11.addWidget(self.radio_cc1)
        self.radio_cv1 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radio_cv1.setObjectName("radio_cv1")
        self.horizontalLayout_11.addWidget(self.radio_cv1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.doubleSpinBox_setval = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_setval.setMaximum(35.0)
        self.doubleSpinBox_setval.setSingleStep(0.01)
        self.doubleSpinBox_setval.setObjectName("doubleSpinBox_setval")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_setval)
        self.pushButton_setval = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_setval.setObjectName("pushButton_setval")
        self.horizontalLayout_12.addWidget(self.pushButton_setval)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_deviceControl)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radio_currinc = QtWidgets.QRadioButton(self.groupBox_8)
        self.radio_currinc.setChecked(True)
        self.radio_currinc.setObjectName("radio_currinc")
        self.horizontalLayout_16.addWidget(self.radio_currinc)
        self.radio_voltinc = QtWidgets.QRadioButton(self.groupBox_8)
        self.radio_voltinc.setObjectName("radio_voltinc")
        self.horizontalLayout_16.addWidget(self.radio_voltinc)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.doubleSpinBox_setincr = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_setincr.setMaximum(35.0)
        self.doubleSpinBox_setincr.setSingleStep(0.01)
        self.doubleSpinBox_setincr.setObjectName("doubleSpinBox_setincr")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_setincr)
        self.pushButton_setincr = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_setincr.setObjectName("pushButton_setincr")
        self.horizontalLayout_14.addWidget(self.pushButton_setincr)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_subincr = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_subincr.setObjectName("pushButton_subincr")
        self.horizontalLayout_15.addWidget(self.pushButton_subincr)
        self.pushButton_addincr = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_addincr.setObjectName("pushButton_addincr")
        self.horizontalLayout_15.addWidget(self.pushButton_addincr)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_deviceControl)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_target = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_target.setDecimals(3)
        self.doubleSpinBox_target.setSingleStep(0.01)
        self.doubleSpinBox_target.setProperty("value", 0.3)
        self.doubleSpinBox_target.setObjectName("doubleSpinBox_target")
        self.gridLayout.addWidget(self.doubleSpinBox_target, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.doubleSpinBox_autoincr = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_autoincr.setDecimals(3)
        self.doubleSpinBox_autoincr.setSingleStep(0.01)
        self.doubleSpinBox_autoincr.setProperty("value", 0.001)
        self.doubleSpinBox_autoincr.setObjectName("doubleSpinBox_autoincr")
        self.gridLayout.addWidget(self.doubleSpinBox_autoincr, 1, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.spinBox_dwell = QtWidgets.QSpinBox(self.tab)
        self.spinBox_dwell.setMaximum(1000)
        self.spinBox_dwell.setProperty("value", 200)
        self.spinBox_dwell.setObjectName("spinBox_dwell")
        self.gridLayout.addWidget(self.spinBox_dwell, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 2)
        self.pushButton_startramp = QtWidgets.QPushButton(self.tab)
        self.pushButton_startramp.setObjectName("pushButton_startramp")
        self.gridLayout.addWidget(self.pushButton_startramp, 3, 0, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_smoothtarget = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_smoothtarget.setMaximum(5.0)
        self.doubleSpinBox_smoothtarget.setSingleStep(0.01)
        self.doubleSpinBox_smoothtarget.setProperty("value", 1.0)
        self.doubleSpinBox_smoothtarget.setObjectName("doubleSpinBox_smoothtarget")
        self.gridLayout_3.addWidget(self.doubleSpinBox_smoothtarget, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.doubleSpinBox_smoothrate = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_smoothrate.setDecimals(3)
        self.doubleSpinBox_smoothrate.setMinimum(0.001)
        self.doubleSpinBox_smoothrate.setMaximum(10.0)
        self.doubleSpinBox_smoothrate.setProperty("value", 1.0)
        self.doubleSpinBox_smoothrate.setObjectName("doubleSpinBox_smoothrate")
        self.gridLayout_3.addWidget(self.doubleSpinBox_smoothrate, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        self.spinBox_smoothdwell = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_smoothdwell.setMinimum(1)
        self.spinBox_smoothdwell.setMaximum(1000)
        self.spinBox_smoothdwell.setProperty("value", 100)
        self.spinBox_smoothdwell.setObjectName("spinBox_smoothdwell")
        self.gridLayout_3.addWidget(self.spinBox_smoothdwell, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 1, 1, 1)
        self.pushButton_smoothrampstart = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_smoothrampstart.setObjectName("pushButton_smoothrampstart")
        self.gridLayout_3.addWidget(self.pushButton_smoothrampstart, 3, 0, 1, 1)
        self.pushButton_showtrajectorie = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_showtrajectorie.setObjectName("pushButton_showtrajectorie")
        self.gridLayout_3.addWidget(self.pushButton_showtrajectorie, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_lintarget = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_lintarget.setDecimals(3)
        self.doubleSpinBox_lintarget.setProperty("value", 1.0)
        self.doubleSpinBox_lintarget.setObjectName("doubleSpinBox_lintarget")
        self.gridLayout_4.addWidget(self.doubleSpinBox_lintarget, 0, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 2, 1, 1)
        self.doubleSpinBox_linrate = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_linrate.setDecimals(3)
        self.doubleSpinBox_linrate.setProperty("value", 1.0)
        self.doubleSpinBox_linrate.setObjectName("doubleSpinBox_linrate")
        self.gridLayout_4.addWidget(self.doubleSpinBox_linrate, 1, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 2, 1, 1)
        self.spinBox_lindwell = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_lindwell.setMinimum(1)
        self.spinBox_lindwell.setMaximum(1000)
        self.spinBox_lindwell.setProperty("value", 10)
        self.spinBox_lindwell.setObjectName("spinBox_lindwell")
        self.gridLayout_4.addWidget(self.spinBox_lindwell, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 2, 1, 1)
        self.pushButton_linrampstart = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_linrampstart.setObjectName("pushButton_linrampstart")
        self.gridLayout_4.addWidget(self.pushButton_linrampstart, 4, 0, 1, 1)
        self.pushButton_linrampshowtrajectory = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_linrampshowtrajectory.setObjectName("pushButton_linrampshowtrajectory")
        self.gridLayout_4.addWidget(self.pushButton_linrampshowtrajectory, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_20.addWidget(self.tabWidget)
        self.horizontalLayout_8.addWidget(self.groupBox_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_3.addWidget(self.groupBox_deviceControl)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_1 = PlotWidget(self.widget_3)
        self.plot_1.setObjectName("plot_1")
        self.verticalLayout_2.addWidget(self.plot_1)
        self.plot_2 = PlotWidget(self.widget_3)
        self.plot_2.setObjectName("plot_2")
        self.verticalLayout_2.addWidget(self.plot_2)
        self.plot_3 = PlotWidget(self.widget_3)
        self.plot_3.setObjectName("plot_3")
        self.verticalLayout_2.addWidget(self.plot_3)
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Device Connection"))
        self.label.setText(_translate("MainWindow", "Resource Name"))
        self.lineEdit_resource.setText(_translate("MainWindow", "TCPIP0::169.254.70.222::9221::SOCKET"))
        self.label_deviceName.setText(_translate("MainWindow", "<connected to>"))
        self.checkBox_connect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Device Status"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Channel 1"))
        self.label_2.setText(_translate("MainWindow", "Voltage"))
        self.label_3.setText(_translate("MainWindow", "Current"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Channel 2"))
        self.label_4.setText(_translate("MainWindow", "Voltage"))
        self.label_5.setText(_translate("MainWindow", "Current"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Channel 3"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.label_7.setText(_translate("MainWindow", "Current"))
        self.groupBox_deviceControl.setTitle(_translate("MainWindow", "Device Control"))
        self.checkBox_output.setText(_translate("MainWindow", "Output ON/OFF"))
        self.checkBox_automaticcontrol.setText(_translate("MainWindow", "Automatic Control"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Channel 1"))
        self.radio_cc1.setText(_translate("MainWindow", "Current"))
        self.radio_cv1.setText(_translate("MainWindow", "Voltage"))
        self.pushButton_setval.setText(_translate("MainWindow", "Set"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Increment"))
        self.radio_currinc.setText(_translate("MainWindow", "Current"))
        self.radio_voltinc.setText(_translate("MainWindow", "Voltage"))
        self.pushButton_setincr.setText(_translate("MainWindow", "Set"))
        self.pushButton_subincr.setText(_translate("MainWindow", "decrement (-)"))
        self.pushButton_addincr.setText(_translate("MainWindow", "increment (+)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Automatic Current Ramp"))
        self.label_9.setText(_translate("MainWindow", "Target (A)"))
        self.label_8.setText(_translate("MainWindow", "Inc. (A)"))
        self.label_10.setText(_translate("MainWindow", "Dwell (ms)"))
        self.pushButton_startramp.setText(_translate("MainWindow", "Ramp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Increment"))
        self.label_11.setText(_translate("MainWindow", "Target Current (A)"))
        self.label_12.setText(_translate("MainWindow", "Rate (A/min)"))
        self.label_13.setText(_translate("MainWindow", "Dwell (ms)"))
        self.pushButton_smoothrampstart.setText(_translate("MainWindow", "Start Ramp"))
        self.pushButton_showtrajectorie.setText(_translate("MainWindow", "Preview Trajectorie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Smooth  Edge Lin"))
        self.label_14.setText(_translate("MainWindow", "Target (A)"))
        self.label_15.setText(_translate("MainWindow", "Rate (A/min)"))
        self.label_16.setText(_translate("MainWindow", "Dwell (ms)"))
        self.pushButton_linrampstart.setText(_translate("MainWindow", "Start Rmp"))
        self.pushButton_linrampshowtrajectory.setText(_translate("MainWindow", "Preview Trajectory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Lin"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
